# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [2]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [3]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [4]:
print(a[2])

300

What are the values of index for series a?

In [5]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [6]:
a.index = ['c', 'a', 'b', 'd']
a

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [7]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [8]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [9]:
b = pd.Series([800, 450, 100], index = ['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [10]:
a = pd.concat([a,b])

In [11]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [12]:
sorted_a = a.sort_values(ascending = False)
print(sorted_a)

e    800
f    450
d    400
b    300
a    200
c    100
g    100
dtype: int64

In [13]:
print(sorted_a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [14]:
df = pd.DataFrame(a)

In [15]:
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [16]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [17]:
# yep its same as the series.

df.index

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [18]:
df.head()

# head is used to show first values of the dataset

     0
c  100
a  200
b  300
d  400
e  800

In [19]:
df.tail()

# tail is used to show the last values

     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [20]:
df.columns = ['points']
print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [21]:
#Create fruits array

fruits = ['Orange', 'Mango', 'Apple']

In [22]:
#Create series fruits out of fruits array

fruits = pd.Series(np.random.choice(['Orange','Mango','Apple'],7))
fruits

0     Apple
1    Orange
2    Orange
3     Mango
4     Mango
5     Mango
6     Mango
dtype: object

Change the index of fruits to the index of dataframe df

In [23]:
fruits.index = df.index

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [24]:
df['fruits'] = fruits

In [25]:
df.head()

   points  fruits
c     100   Apple
a     200  Orange
b     300  Orange
d     400   Mango
e     800   Mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [26]:
d1 = pd.DataFrame({'city':['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
                   'Temperature':[15,22,20,26,-2]})

Print(d1)

In [27]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [28]:
d1.shape

(5, 2)

Set city = d1['city']

In [29]:
city = d1['city']

print city <br>
What is the type of city.

In [30]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [31]:
d2 = pd.DataFrame({'city':['Bengaluru','Coimbatore','Srirangam','Pondicherry'],
                   'Temperature':[24,33,36,39]})

print the shape of this dataframe

In [32]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [33]:
d3 = pd.concat([d1,d2])
d3

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengaluru           24
1   Coimbatore           33
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [34]:
d3[d3['Temperature'] <= 20]
print("Number of cities:", len(d3[d3['Temperature'] <= 20]))

Number of cities: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [35]:
d3[d3['Temperature'] >= 35]
print("Number of cities:", len(d3[d3['Temperature'] >= 35]))

Number of cities: 2

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [36]:
# write function here    
# write code below

def is_ut(x):
    ut_cities = ['Chandigarh', 'Delhi', 'Pondicherry']
    if x in ut_cities:
        return True
    else:
        return False

d3['is_ut'] = d3['city'].apply(is_ut)

In [37]:
# print d3

d3

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengaluru           24  False
1   Coimbatore           33  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [38]:
# write function here

def c_to_f(temp):
    return (temp * 9/5) + 32

In [39]:
# check function c_to_f(10)

c_to_f(10)

50.0

In [40]:
# apply function c_to_f to d3 to create a column 'temp_fahrenheit'

d3['temp_fahrenheit'] = d3['Temperature'].apply(c_to_f)

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [41]:
d3[d3['is_ut'] == True]

          city  Temperature  is_ut  temp_fahrenheit
0   Chandigarh           15   True             59.0
1        Delhi           22   True             71.6
3  Pondicherry           39   True            102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [42]:
d3[d3['temp_fahrenheit'] > 90]

          city  Temperature  is_ut  temp_fahrenheit
1   Coimbatore           33  False             91.4
2    Srirangam           36  False             96.8
3  Pondicherry           39   True            102.2

Select only the first three rows of the dataframe d1.

In [43]:
d1.head(3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [44]:
d1.iloc[:, -2:]

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [45]:
# Create a dataframe using dictionary of your choice

data = {'Department':['IT','IT','HR','HR','Finance','Finance'],
        'Employee':['A','B','C','D','E','F'],
        'Salary':[50000,60000,48000,45000,50000,55000]
       }

df_group = pd.DataFrame(data)
df_group

  Department Employee  Salary
0         IT        A   50000
1         IT        B   60000
2         HR        C   48000
3         HR        D   45000
4    Finance        E   50000
5    Finance        F   55000

In [46]:
# Use Groupby of single column with aggregate sum()

df_group.groupby('Department')['Salary'].sum()

Department
Finance    105000
HR          93000
IT         110000
Name: Salary, dtype: int64

In [47]:
# Use Groupby of single column with aggregate count()

df_group.groupby('Department')['Salary'].count()

Department
Finance    2
HR         2
IT         2
Name: Salary, dtype: int64

In [48]:
# Use Groupby of single column with aggregate min() and max()


df_group.groupby('Department')['Salary'].agg(['min','max'])

              min    max
Department
Finance     50000  55000
HR          45000  48000
IT          50000  60000

In [49]:
# Use Groupby of any 2 columns with aggregate mean()

df_group.groupby(['Department','Employee'])['Salary'].mean()

Department  Employee
Finance     E           50000.0
            F           55000.0
HR          C           48000.0
            D           45000.0
IT          A           50000.0
            B           60000.0
Name: Salary, dtype: float64

In [50]:
# Use Groupby of any 2 columns with aggregate min() and max()

df_group.groupby(['Department','Employee'])['Salary'].agg(['min','max'])

                       min    max
Department Employee
Finance    E         50000  50000
           F         55000  55000
HR         C         48000  48000
           D         45000  45000
IT         A         50000  50000
           B         60000  60000

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [51]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [52]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [53]:
print(len(a))

457

What is the type of a?

In [54]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>